// Frases del día (originales). Se muestra una distinta cada día en «Hoy».
window.FRASES = [
  'Eres la prueba de que se puede con todo: con la consulta, con la casa y con el corazón lleno.',
  'Tu fuerza no hace ruido, pero sostiene a muchos.',
  'Cada paciente que sale mejor de tu consultorio lleva un pedacito de tu valentía.',
  'Hoy no tienes que ser perfecta; ya eres suficiente.',
  'Las mujeres fuertes no nacen sin miedo: aprenden a avanzar con él.',
  'Eres médica, mamá y guerrera. Ninguna capa te queda grande.',
  'Lo que hoy parece pesado, mañana será la historia de cómo lo lograste.',
  'Tus hijos aprenden lo que es la valentía viéndote a ti.',
  'Cuidar a otros es un superpoder; no olvides usarlo también contigo.',
  'Has superado cada día difícil hasta hoy. Llevas una racha perfecta.',
  'Tu calma en medio del caos es una forma de liderazgo.',
  'La fuerza femenina no se mide en lo que cargas, sino en cómo te levantas.',
  'Eres raíz para tu familia y alas para tus sueños.',
  'Cada adversidad que enfrentas te recuerda de qué estás hecha.',
  'Ser súper mamá no es no cansarse; es seguir amando aun cansada.',
  'Tu vocación cambia vidas, empezando por la de quienes te ven trabajar.',
  'No hay montaña tan alta como la determinación de una mujer que decidió subirla.',
  'Hoy tu sonrisa puede ser la mejor medicina para alguien.',
  'Eres capaz de cosas que todavía no imaginas.',
  'Tu historia está llena de días que creíste imposibles, y los venciste.',
  'Mujer que se cuida, cuida mejor. Date también tu propia consulta.',
  'Las grandes mujeres no esperan a que pase la tormenta: aprenden a avanzar bajo la lluvia.',
  'En casa eres refugio; en el consultorio, esperanza.',
  'La valentía también se ve como una bata blanca a primera hora de la mañana.',
  'Confía en ti: tu conocimiento, tu intuición y tu corazón trabajan en equipo.',
  'Cada «sí puedo» que te dices es una semilla de algo grande.',
  'Ser mamá te dio un corazón más grande; ser médica, unas manos que sanan.',
  'No eres frágil: eres flexible, y eso te hace invencible.',
  'Hoy elige avanzar, aunque sea un paso. Los pasos pequeños también llegan lejos.',
  'Tu esfuerzo de hoy es el ejemplo que tus hijos recordarán mañana.',
  'La fortaleza de una mujer se nota en cómo sigue siendo amable en los días difíciles.',
  'Eres de las que convierten los obstáculos en escalones.',
  'Que nada apague la luz con la que atiendes a cada persona.',
  'Ser súper mamá no significa hacerlo todo; significa hacerlo con amor.',
  'Lo que siembras con paciencia florece con fuerza.',
  'Tu presencia ya es un regalo para quienes atiendes.',
  'Hay mujeres que inspiran sin proponérselo. Tú eres una de ellas.',
  'Cuando dudes de ti, recuerda todo lo que ya has superado.',
  'Ninguna adversidad es más grande que tu capacidad de salir adelante.',
  'El mundo necesita médicas valientes y mamás que no se rinden. Tú eres ambas.',
  'Cansada, sí. Vencida, nunca.',
  'Tu ternura y tu fuerza no compiten: se complementan.',
  'Hoy es un buen día para sentirte orgullosa de ti.',
  'Detrás de cada mujer fuerte hay batallas que nadie vio. Y las ganó.',
  'Eres capaz, eres valiosa y eres necesaria.',
  'Tus manos sanan, tus palabras calman y tu ejemplo enseña.',
  'Levantarte una y otra vez es tu forma natural de ser.',
  'Las súper mamás también descansan; recargar es parte del poder.',
  'Cuando una mujer cree en sí misma, todo a su alrededor empieza a acomodarse.',
  'Hoy vas a lograr más de lo que crees.',
  'Tu fuerza viene de adentro, y nadie te la puede quitar.',
  'Eres el lugar seguro de tus hijos y la esperanza de tus pacientes.',
  'Las dificultades no te definen; tu manera de enfrentarlas, sí.',
  'Sé amable contigo: estás haciendo un trabajo extraordinario.',
  'Lo imposible solo tarda un poco más cuando lo intenta una mujer decidida.',
  'Cada mañana te eliges valiente. Eso ya es una victoria.',
  'Tu vocación es servir, y tu poder es no rendirte.',
  'Mujer que sana a otros: que hoy alguien también cuide de ti.',
  'Tus sueños no tienen fecha de caducidad, y tu fuerza tampoco.',
  'Puedes con todo, y también sabes pedir ayuda. Eso es sabiduría.'
];
