// Catálogo base de diagnósticos del formato SUIVE-1 (Informe semanal de casos nuevos de enfermedades).
// Se carga solo la primera vez; después vive en la base local y se edita desde Configuración.
// Verificar contra el formato SUIVE-1 vigente de la jurisdicción.
window.SUIVE_BASE = [
  // Infecciosas y parasitarias del aparato digestivo
  ["A00", "Cólera", "Aparato digestivo"],
  ["A01.0", "Fiebre tifoidea", "Aparato digestivo"],
  ["A01.1-A01.4", "Fiebre paratifoidea", "Aparato digestivo"],
  ["A02", "Otras salmonelosis", "Aparato digestivo"],
  ["A03", "Shigelosis", "Aparato digestivo"],
  ["A04, A08-A09", "Infecciones intestinales por otros organismos y las mal definidas", "Aparato digestivo"],
  ["A05", "Intoxicación alimentaria bacteriana", "Aparato digestivo"],
  ["A06.0-A06.3, A06.9", "Amebiasis intestinal", "Aparato digestivo"],
  ["A06.4", "Absceso hepático amebiano", "Aparato digestivo"],
  ["A07.1", "Giardiasis", "Aparato digestivo"],
  ["A07.0, A07.2-A07.9", "Otras infecciones intestinales debidas a protozoarios", "Aparato digestivo"],
  ["B77", "Ascariasis", "Aparato digestivo"],
  ["B80", "Enterobiasis", "Aparato digestivo"],
  ["B68", "Teniasis", "Aparato digestivo"],
  ["B69", "Cisticercosis", "Aparato digestivo"],
  ["B65-B67, B70-B76, B78-B79, B81-B83", "Otras helmintiasis", "Aparato digestivo"],
  ["B15", "Hepatitis viral A", "Aparato digestivo"],
  ["B16, B18.0-B18.1", "Hepatitis viral B", "Aparato digestivo"],
  ["B17.1, B18.2", "Hepatitis viral C", "Aparato digestivo"],
  ["B17.2", "Hepatitis viral E", "Aparato digestivo"],
  ["B17, B19", "Otras hepatitis virales", "Aparato digestivo"],
  ["K25-K29", "Úlceras, gastritis y duodenitis", "Aparato digestivo"],
  ["K05", "Gingivitis y enfermedad periodontal", "Aparato digestivo"],
  ["K70, K74", "Enfermedad alcohólica del hígado y cirrosis", "Aparato digestivo"],

  // Aparato respiratorio
  ["J00-J06, J20-J21 (excepto J02.0, J03.0)", "Infecciones respiratorias agudas", "Aparato respiratorio"],
  ["J02.0, J03.0", "Faringitis y amigdalitis estreptocócicas", "Aparato respiratorio"],
  ["H65.0-H65.1", "Otitis media aguda", "Aparato respiratorio"],
  ["J12-J18 (excepto J18.2)", "Neumonías y bronconeumonías", "Aparato respiratorio"],
  ["J09-J11", "Influenza", "Aparato respiratorio"],
  ["U07.1", "COVID-19", "Aparato respiratorio"],
  ["A15-A16", "Tuberculosis respiratoria", "Aparato respiratorio"],
  ["J45-J46", "Asma", "Aparato respiratorio"],
  ["J40-J44", "Enfermedad pulmonar obstructiva crónica", "Aparato respiratorio"],

  // Transmisión sexual
  ["A50", "Sífilis congénita", "Transmisión sexual"],
  ["A51-A53", "Sífilis adquirida", "Transmisión sexual"],
  ["A54", "Infección gonocócica del tracto genitourinario", "Transmisión sexual"],
  ["A55", "Linfogranuloma venéreo", "Transmisión sexual"],
  ["A57", "Chancro blando", "Transmisión sexual"],
  ["A59.0", "Tricomoniasis urogenital", "Transmisión sexual"],
  ["A60.0", "Herpes genital", "Transmisión sexual"],
  ["B37.3-B37.4", "Candidiasis urogenital", "Transmisión sexual"],
  ["B97.7", "Infección por virus del papiloma humano", "Transmisión sexual"],
  ["B20-B24", "VIH / SIDA", "Transmisión sexual"],
  ["Z21", "Infección asintomática por VIH", "Transmisión sexual"],

  // Transmitidas por vector
  ["A97.0-A97.1", "Dengue no grave / con signos de alarma", "Transmitidas por vector"],
  ["A97.2", "Dengue grave", "Transmitidas por vector"],
  ["A92.0", "Fiebre chikungunya", "Transmitidas por vector"],
  ["A92.8, U06.9", "Enfermedad por virus Zika", "Transmitidas por vector"],
  ["B50-B54", "Paludismo", "Transmitidas por vector"],
  ["B57", "Enfermedad de Chagas", "Transmitidas por vector"],
  ["B55", "Leishmaniasis", "Transmitidas por vector"],
  ["B73", "Oncocercosis", "Transmitidas por vector"],
  ["A77.0", "Fiebre manchada", "Transmitidas por vector"],
  ["A75", "Tifo epidémico y murino", "Transmitidas por vector"],
  ["A92.3", "Fiebre del Nilo Occidental", "Transmitidas por vector"],

  // Zoonosis
  ["A23", "Brucelosis", "Zoonosis"],
  ["A82", "Rabia humana", "Zoonosis"],
  ["A27", "Leptospirosis", "Zoonosis"],
  ["B75", "Triquinosis", "Zoonosis"],
  ["B67", "Equinococosis", "Zoonosis"],

  // Prevenibles por vacunación y exantemáticas
  ["B05", "Sarampión", "Prevenibles por vacunación"],
  ["B06", "Rubéola", "Prevenibles por vacunación"],
  ["P35.0", "Síndrome de rubéola congénita", "Prevenibles por vacunación"],
  ["B01", "Varicela", "Prevenibles por vacunación"],
  ["B02", "Herpes zóster", "Prevenibles por vacunación"],
  ["B26", "Parotiditis infecciosa", "Prevenibles por vacunación"],
  ["A37", "Tos ferina", "Prevenibles por vacunación"],
  ["A36", "Difteria", "Prevenibles por vacunación"],
  ["A35", "Tétanos", "Prevenibles por vacunación"],
  ["A33", "Tétanos neonatal", "Prevenibles por vacunación"],
  ["A80", "Poliomielitis aguda / parálisis flácida aguda", "Prevenibles por vacunación"],
  ["A17.0", "Tuberculosis meníngea", "Prevenibles por vacunación"],
  ["A39.0", "Meningitis meningocócica", "Prevenibles por vacunación"],
  ["G00.0", "Meningitis por Haemophilus influenzae", "Prevenibles por vacunación"],
  ["A38", "Escarlatina", "Prevenibles por vacunación"],

  // Otras transmisibles
  ["N30, N34, N39.0", "Infección de vías urinarias", "Otras transmisibles"],
  ["N76", "Vulvovaginitis", "Otras transmisibles"],
  ["H10", "Conjuntivitis", "Otras transmisibles"],
  ["A46", "Erisipela", "Otras transmisibles"],
  ["B86", "Escabiosis", "Otras transmisibles"],
  ["B85", "Pediculosis", "Otras transmisibles"],
  ["A30", "Lepra", "Otras transmisibles"],
  ["A17.1-A19 (excepto A17.0)", "Tuberculosis otras formas", "Otras transmisibles"],
  ["A87, G00-G03 (excepto G00.0)", "Meningitis (otras)", "Otras transmisibles"],
  ["A48.1", "Legionelosis", "Otras transmisibles"],
  ["I00-I02", "Fiebre reumática aguda", "Otras transmisibles"],

  // No transmisibles
  ["E10", "Diabetes mellitus tipo 1", "No transmisibles"],
  ["E11-E14", "Diabetes mellitus tipo 2", "No transmisibles"],
  ["O24.4", "Diabetes mellitus en el embarazo", "No transmisibles"],
  ["I10-I15", "Hipertensión arterial", "No transmisibles"],
  ["O10-O16", "Edema, proteinuria y trastornos hipertensivos en el embarazo", "No transmisibles"],
  ["I20-I25", "Enfermedad isquémica del corazón", "No transmisibles"],
  ["I60-I67, I69", "Enfermedad cerebrovascular", "No transmisibles"],
  ["I05-I09", "Enfermedades cardíacas reumáticas crónicas", "No transmisibles"],
  ["I87.2", "Insuficiencia venosa periférica", "No transmisibles"],
  ["E66", "Obesidad", "No transmisibles"],
  ["E44.1", "Desnutrición leve", "No transmisibles"],
  ["E44.0", "Desnutrición moderada", "No transmisibles"],
  ["E40-E43", "Desnutrición severa", "No transmisibles"],
  ["E01", "Bocio endémico", "No transmisibles"],
  ["E03.1", "Hipotiroidismo congénito", "No transmisibles"],
  ["N18", "Enfermedad renal crónica", "No transmisibles"],
  ["G40-G41", "Epilepsia", "No transmisibles"],
  ["G20", "Enfermedad de Parkinson", "No transmisibles"],
  ["G30", "Enfermedad de Alzheimer", "No transmisibles"],

  // Tumores y displasias
  ["C50", "Tumor maligno de la mama", "Tumores"],
  ["C53", "Tumor maligno del cuello del útero", "Tumores"],
  ["N87.0-N87.1", "Displasia cervical leve y moderada", "Tumores"],
  ["D06, N87.2", "Displasia cervical severa y CaCu in situ", "Tumores"],
  ["C61", "Tumor maligno de la próstata", "Tumores"],

  // Salud mental
  ["F32", "Depresión", "Salud mental"],
  ["F50", "Anorexia, bulimia y otros trastornos alimentarios", "Salud mental"],
  ["F41", "Trastornos de ansiedad", "Salud mental"],

  // Lesiones, intoxicaciones y causas externas
  ["V20-V29", "Accidentes de transporte en motocicleta", "Lesiones y causas externas"],
  ["V01-V89 (excepto V20-V29)", "Accidentes de transporte en vehículos con motor", "Lesiones y causas externas"],
  ["W54", "Mordeduras por perro", "Lesiones y causas externas"],
  ["W53, W55", "Mordeduras por otros mamíferos", "Lesiones y causas externas"],
  ["X20, T63.0", "Mordedura por serpiente", "Lesiones y causas externas"],
  ["T63.2, X22", "Intoxicación por picadura de alacrán", "Lesiones y causas externas"],
  ["T63.1, T63.3-T63.9", "Intoxicación por ponzoña de otros animales", "Lesiones y causas externas"],
  ["T60", "Intoxicación aguda por plaguicidas", "Lesiones y causas externas"],
  ["T58", "Intoxicación por monóxido de carbono", "Lesiones y causas externas"],
  ["T51-T65 (excepto T58, T60, T63)", "Efecto tóxico de otras sustancias", "Lesiones y causas externas"],
  ["T20-T32", "Quemaduras", "Lesiones y causas externas"],
  ["T67", "Efectos del calor (golpe de calor, agotamiento)", "Lesiones y causas externas"],
  ["T68-T69", "Hipotermia y efectos del frío", "Lesiones y causas externas"],
  ["Y07.0-Y07.2", "Violencia intrafamiliar", "Lesiones y causas externas"],
  ["X85-Y09 (excepto Y07)", "Lesiones por violencia (otras)", "Lesiones y causas externas"],
  ["W65-W74", "Ahogamiento y sumersión", "Lesiones y causas externas"]
];
